### ISSUE TITLE
Концепция корпуса и дизайн

### ISSUE THREAD

**Issue by slavikyd** [slavikyd/project-Martian-Wayfarer#4]

**Comment by chai1s1saxarom** [comment]
![Славе_нрав_НОги2](https://github.com/slavikyd/project-Martian-Wayfarer/assets/151803344/870dadef-7dfd-49b3-ae40-36b90070a976)
![Слава_одобрил_концепт_ураураура](https://github.com/slavikyd/project-Martian-Wayfarer/assets/151803344/634c5a2e-3d3f-4a67-9793-b3cacfcb9815)

**Comment by slavikyd** [comment]
Добавить рендеры, а так в целом тут все
